export const MOCK_USERS = [
  {
    user_id: 'test-buyer-1',
    name: 'Olu Jones',
    phone: '+23276123456',
    email: 'olujonesvidal@gmail.com',
    role: 'buyer',
    farm_name: null,
    location: 'Freetown',
    verified: true,
  },
  {
    user_id: 'demo_customer',
    name: 'Demo Customer',
    phone: '+23270000010',
    email: 'customer@demo.com',
    role: 'buyer',
    farm_name: null,
    location: 'Demo City',
    verified: true,
  },
  {
    user_id: 'demo_admin',
    name: 'Demo Admin',
    phone: '+23270000011',
    email: 'admin@demo.com',
    role: 'admin',
    farm_name: null,
    location: 'Demo HQ',
    verified: true,
  },
  {
    user_id: 'demo_farmer',
    name: 'Demo Farmer',
    phone: '+23270000012',
    email: 'farmer@demo.com',
    role: 'farmer',
    farm_name: 'Demo Farm',
    location: 'Demo Village',
    verified: true,
  },
  {
    user_id: 'user_buyer_1',
    name: 'Ama Johnson',
    phone: '+23270000001',
    email: 'ama@example.com',
    role: 'buyer',
    farm_name: null,
    location: 'Freetown',
    verified: true,
  },
  {
    user_id: 'user_farmer_1',
    name: 'Joseph Sesay',
    phone: '+23270000002',
    email: 'joseph@example.com',
    role: 'farmer',
    farm_name: 'Green Acres Farm',
    location: 'Kissy',
    verified: true,
  },
  {
    user_id: 'user_farmer_2',
    name: 'Fatmata Conteh',
    phone: '+23270000003',
    email: 'fatmata@example.com',
    role: 'farmer',
    farm_name: 'Sunrise Harvest',
    location: 'Bo',
    verified: true,
  },
];

export const MOCK_PRODUCTS = [
  {
    product_id: 'prod_1',
    name: 'Brown Rice',
    description: 'High-quality brown rice harvested locally each week.',
    price: 25.0,
    unit: 'kg',
    quantity: 120,
    image_url: 'https://placehold.co/400x240/8BC34A/FFFFFF/png?text=Brown+Rice',
    farmer_id: 'user_farmer_1',
    category: 'Grains',
    status: 'active',
    created_at: new Date().toISOString(),
    users: { name: 'Joseph Sesay', location: 'Kissy' },
  },
  {
    product_id: 'prod_2',
    name: 'Sweet Bananas',
    description: 'Sweet ripe bananas sold in fresh bunches.',
    price: 9.5,
    unit: 'bunch',
    quantity: 80,
    image_url: 'https://placehold.co/400x240/FFB74D/FFFFFF/png?text=Bananas',
    farmer_id: 'user_farmer_2',
    category: 'Fruits',
    status: 'active',
    created_at: new Date().toISOString(),
    users: { name: 'Fatmata Conteh', location: 'Bo' },
  },
  {
    product_id: 'prod_3',
    name: 'Red Tomatoes',
    description: 'Fresh vine-ripened tomatoes from local growers.',
    price: 6.0,
    unit: 'kg',
    quantity: 90,
    image_url: 'https://placehold.co/400x240/F44336/FFFFFF/png?text=Tomatoes',
    farmer_id: 'user_farmer_1',
    category: 'Vegetables',
    status: 'active',
    created_at: new Date().toISOString(),
    users: { name: 'Joseph Sesay', location: 'Kissy' },
  },
  {
    product_id: 'prod_4',
    name: 'Irish Potatoes',
    description: 'Fresh tubers hand-picked for quality and taste.',
    price: 18.0,
    unit: 'kg',
    quantity: 64,
    image_url: 'https://placehold.co/400x240/795548/FFFFFF/png?text=Potatoes',
    farmer_id: 'user_farmer_2',
    category: 'Tubers',
    status: 'active',
    created_at: new Date().toISOString(),
    users: { name: 'Fatmata Conteh', location: 'Bo' },
  },
  {
    product_id: 'prod_5',
    name: 'Fresh Carrots',
    description: 'Crunchy orange carrots ideal for stews and salads.',
    price: 12.0,
    unit: 'kg',
    quantity: 50,
    image_url: 'https://placehold.co/400x240/FFA726/FFFFFF/png?text=Carrots',
    farmer_id: 'user_farmer_1',
    category: 'Vegetables',
    status: 'active',
    created_at: new Date().toISOString(),
    users: { name: 'Joseph Sesay', location: 'Kissy' },
  },
  {
    product_id: 'prod_6',
    name: 'Ripe Mangoes',
    description: 'Sweet mangoes perfect for smoothies and desserts.',
    price: 14.0,
    unit: 'piece',
    quantity: 70,
    image_url: 'https://placehold.co/400x240/FFEB3B/000000/png?text=Mangoes',
    farmer_id: 'user_farmer_2',
    category: 'Fruits',
    status: 'active',
    created_at: new Date().toISOString(),
    users: { name: 'Fatmata Conteh', location: 'Bo' },
  },
  {
    product_id: 'prod_7',
    name: 'Sweet Potatoes',
    description: 'Naturally sweet and full of nutrients.',
    price: 20.0,
    unit: 'kg',
    quantity: 56,
    image_url: 'https://placehold.co/400x240/FF8A65/FFFFFF/png?text=Sweet+Potatoes',
    farmer_id: 'user_farmer_1',
    category: 'Tubers',
    status: 'active',
    created_at: new Date().toISOString(),
    users: { name: 'Joseph Sesay', location: 'Kissy' },
  },
  {
    product_id: 'prod_8',
    name: 'Green Spinach',
    description: 'Fresh leafy greens for soups and sauces.',
    price: 10.0,
    unit: 'bunch',
    quantity: 120,
    image_url: 'https://placehold.co/400x240/4CAF50/FFFFFF/png?text=Spinach',
    farmer_id: 'user_farmer_2',
    category: 'Vegetables',
    status: 'active',
    created_at: new Date().toISOString(),
    users: { name: 'Fatmata Conteh', location: 'Bo' },
  },
  {
    product_id: 'prod_9',
    name: 'Cassava Tubers',
    description: 'Fresh cassava ready for processing and cooking.',
    price: 15.0,
    unit: 'kg',
    quantity: 90,
    image_url: 'https://placehold.co/400x240/8D6E63/FFFFFF/png?text=Cassava',
    farmer_id: 'user_farmer_1',
    category: 'Tubers',
    status: 'active',
    created_at: new Date().toISOString(),
    users: { name: 'Joseph Sesay', location: 'Kissy' },
  },
  {
    product_id: 'prod_10',
    name: 'Cabbage Heads',
    description: 'Large cabbage heads for family meals.',
    price: 11.0,
    unit: 'piece',
    quantity: 40,
    image_url: 'https://placehold.co/400x240/7CB342/FFFFFF/png?text=Cabbage',
    farmer_id: 'user_farmer_2',
    category: 'Vegetables',
    status: 'active',
    created_at: new Date().toISOString(),
    users: { name: 'Fatmata Conteh', location: 'Bo' },
  },
  {
    product_id: 'prod_11',
    name: 'Juicy Pineapples',
    description: 'Sweet tropical pineapples for fresh juice.',
    price: 16.5,
    unit: 'piece',
    quantity: 30,
    image_url: 'https://placehold.co/400x240/FFC107/000000/png?text=Pineapple',
    farmer_id: 'user_farmer_1',
    category: 'Fruits',
    status: 'active',
    created_at: new Date().toISOString(),
    users: { name: 'Joseph Sesay', location: 'Kissy' },
  },
  {
    product_id: 'prod_12',
    name: 'Red Peppers',
    description: 'Spicy red peppers grown without pesticides.',
    price: 13.5,
    unit: 'kg',
    quantity: 45,
    image_url: 'https://placehold.co/400x240/E91E63/FFFFFF/png?text=Peppers',
    farmer_id: 'user_farmer_2',
    category: 'Vegetables',
    status: 'active',
    created_at: new Date().toISOString(),
    users: { name: 'Fatmata Conteh', location: 'Bo' },
  },
  {
    product_id: 'prod_13',
    name: 'Fresh Ginger',
    description: 'Aromatic ginger ideal for teas and sauces.',
    price: 30.0,
    unit: 'kg',
    quantity: 25,
    image_url: 'https://placehold.co/400x240/FF9800/FFFFFF/png?text=Ginger',
    farmer_id: 'user_farmer_1',
    category: 'Other',
    status: 'active',
    created_at: new Date().toISOString(),
    users: { name: 'Joseph Sesay', location: 'Kissy' },
  },
  {
    product_id: 'prod_14',
    name: 'Green Peas',
    description: 'Fresh green peas packed in bundles.',
    price: 14.0,
    unit: 'kg',
    quantity: 60,
    image_url: 'https://placehold.co/400x240/66BB6A/FFFFFF/png?text=Peas',
    farmer_id: 'user_farmer_2',
    category: 'Vegetables',
    status: 'active',
    created_at: new Date().toISOString(),
    users: { name: 'Fatmata Conteh', location: 'Bo' },
  },
  {
    product_id: 'prod_15',
    name: 'Garden Eggplants',
    description: 'Glossy eggplants picked this morning.',
    price: 17.0,
    unit: 'kg',
    quantity: 55,
    image_url: 'https://placehold.co/400x240/673AB7/FFFFFF/png?text=Eggplant',
    farmer_id: 'user_farmer_1',
    category: 'Vegetables',
    status: 'active',
    created_at: new Date().toISOString(),
    users: { name: 'Joseph Sesay', location: 'Kissy' },
  },
  {
    product_id: 'prod_16',
    name: 'Fresh Breadfruit',
    description: 'Starchy breadfruit ready for roasting and boiling.',
    price: 22.0,
    unit: 'piece',
    quantity: 35,
    image_url: 'https://placehold.co/400x240/009688/FFFFFF/png?text=Breadfruit',
    farmer_id: 'user_farmer_2',
    category: 'Other',
    status: 'active',
    created_at: new Date().toISOString(),
    users: { name: 'Fatmata Conteh', location: 'Bo' },
  },
  {
    product_id: 'prod_17',
    name: 'Fresh Ginger Tea',
    description: 'Handmade ginger tea packs from local herbs.',
    price: 45.0,
    unit: 'pack',
    quantity: 20,
    image_url: 'https://placehold.co/400x240/795548/FFFFFF/png?text=Ginger+Tea',
    farmer_id: 'user_farmer_1',
    category: 'Other',
    status: 'active',
    created_at: new Date().toISOString(),
    users: { name: 'Joseph Sesay', location: 'Kissy' },
  },
  {
    product_id: 'prod_18',
    name: 'Coconut Milk',
    description: 'Fresh coconut milk made locally without preservatives.',
    price: 28.0,
    unit: 'liter',
    quantity: 38,
    image_url: 'https://placehold.co/400x240/4DB6AC/FFFFFF/png?text=Coconut+Milk',
    farmer_id: 'user_farmer_2',
    category: 'Other',
    status: 'active',
    created_at: new Date().toISOString(),
    users: { name: 'Fatmata Conteh', location: 'Bo' },
  },
  {
    product_id: 'prod_19',
    name: 'Fresh Onions',
    description: 'Red onions for soups, sauces, and stews.',
    price: 13.0,
    unit: 'kg',
    quantity: 70,
    image_url: 'https://placehold.co/400x240/EF5350/FFFFFF/png?text=Onions',
    farmer_id: 'user_farmer_1',
    category: 'Vegetables',
    status: 'active',
    created_at: new Date().toISOString(),
    users: { name: 'Joseph Sesay', location: 'Kissy' },
  },
  {
    product_id: 'prod_20',
    name: 'Bell Peppers',
    description: 'Colorful bell peppers for salads and stews.',
    price: 16.0,
    unit: 'kg',
    quantity: 48,
    image_url: 'https://placehold.co/400x240/FF7043/FFFFFF/png?text=Bell+Peppers',
    farmer_id: 'user_farmer_2',
    category: 'Vegetables',
    status: 'active',
    created_at: new Date().toISOString(),
    users: { name: 'Fatmata Conteh', location: 'Bo' },
  },
];

/** Featured items shown in the home "Listed for Sale" carousel */
export const MOCK_LISTED_ITEMS = [
  {
    id: 'prod_1',
    product_id: 'prod_1',
    name: 'Brown Rice',
    description: 'High-quality brown rice harvested locally each week.',
    price: 25.0,
    unit: 'kg',
    quantity: 120,
    image_url: 'https://placehold.co/280x180/1A2420/00E676/png?text=Brown+Rice',
    farmer_id: 'user_farmer_1',
    category: 'Grains',
    status: 'active',
    created_at: new Date().toISOString(),
    users: { name: 'Joseph Sesay', location: 'Kissy' },
  },
  {
    id: 'prod_2',
    product_id: 'prod_2',
    name: 'Sweet Bananas',
    description: 'Sweet ripe bananas sold in fresh bunches.',
    price: 9.5,
    unit: 'bunch',
    quantity: 80,
    image_url: 'https://placehold.co/280x180/1A2420/00E676/png?text=Bananas',
    farmer_id: 'user_farmer_2',
    category: 'Fruits',
    status: 'active',
    created_at: new Date().toISOString(),
    users: { name: 'Fatmata Conteh', location: 'Bo' },
  },
  {
    id: 'prod_3',
    product_id: 'prod_3',
    name: 'Red Tomatoes',
    description: 'Fresh vine-ripened tomatoes from local growers.',
    price: 6.0,
    unit: 'kg',
    quantity: 90,
    image_url: 'https://placehold.co/280x180/1A2420/00E676/png?text=Tomatoes',
    farmer_id: 'user_farmer_1',
    category: 'Vegetables',
    status: 'active',
    created_at: new Date().toISOString(),
    users: { name: 'Joseph Sesay', location: 'Kissy' },
  },
];

export const MOCK_SOLD_ITEMS = [
  {
    product_id: 'sold_1',
    name: 'Organic Cassava',
    price: 18.0,
    unit: 'kg',
    image_url: 'https://placehold.co/280x180/1A2420/00E676/png?text=Cassava',
    sold_at: new Date(Date.now() - 3600000 * 5).toISOString(),
    buyer_name: 'Ama J.',
    farmer_name: 'Joseph Sesay',
    farmer_id: 'user_farmer_1',
  },
  {
    product_id: 'sold_2',
    name: 'Fresh Okra',
    price: 12.5,
    unit: 'bunch',
    image_url: 'https://placehold.co/280x180/1A2420/00E676/png?text=Okra',
    sold_at: new Date(Date.now() - 3600000 * 12).toISOString(),
    buyer_name: 'Olu J.',
    farmer_name: 'Fatmata Conteh',
    farmer_id: 'user_farmer_2',
  },
  {
    product_id: 'sold_3',
    name: 'Local Honey',
    price: 55.0,
    unit: 'jar',
    image_url: 'https://placehold.co/280x180/1A2420/00E676/png?text=Honey',
    sold_at: new Date(Date.now() - 86400000).toISOString(),
    buyer_name: 'Demo Customer',
    farmer_name: 'Joseph Sesay',
    farmer_id: 'user_farmer_1',
  },
];

export const MOCK_ORDERS = [
  {
    order_id: 'order_1',
    order_date: new Date().toISOString(),
    product_id: 'prod_1',
    products: { name: 'Brown Rice', image_url: 'https://placehold.co/100x100/8BC34A/FFFFFF/png?text=Brown+Rice', price: 25.0, unit: 'kg' },
    quantity: 2,
    total_price: 50.0,
    status: 'pending',
    payment_status: 'unpaid',
    buyer_id: 'user_buyer_1',
    farmer_id: 'user_farmer_1',
  },
  {
    order_id: 'order_2',
    order_date: new Date(Date.now() - 86400000 * 2).toISOString(),
    product_id: 'prod_2',
    products: { name: 'Sweet Bananas', image_url: 'https://placehold.co/100x100/FFB74D/FFFFFF/png?text=Bananas', price: 9.5, unit: 'bunch' },
    quantity: 1,
    total_price: 9.5,
    status: 'confirmed',
    payment_status: 'paid',
    buyer_id: 'user_buyer_1',
    farmer_id: 'user_farmer_2',
  },
  {
    order_id: 'order_3',
    order_date: new Date(Date.now() - 86400000 * 4).toISOString(),
    product_id: 'prod_3',
    products: { name: 'Red Tomatoes', image_url: 'https://placehold.co/100x100/F44336/FFFFFF/png?text=Tomatoes', price: 6.0, unit: 'kg' },
    quantity: 3,
    total_price: 18.0,
    status: 'shipped',
    payment_status: 'paid',
    buyer_id: 'user_buyer_1',
    farmer_id: 'user_farmer_1',
  },
];

export function findMockProduct(productId: string) {
  const all = [...MOCK_LISTED_ITEMS, ...MOCK_PRODUCTS];
  return all.find((p) => p.product_id === productId || (p as { id?: string }).id === productId) || null;
}

export default {
  MOCK_USERS,
  MOCK_PRODUCTS,
  MOCK_LISTED_ITEMS,
  MOCK_SOLD_ITEMS,
  MOCK_ORDERS,
  findMockProduct,
};
